export const CREATE_PRODUCT = "PRODUCT/CREATE_PRODUCT"
export const GET_PRODUCT = "PRODUCT/GET_PRODUCT"
export const GET_ONE_PRODUCT = "PRODUCT/GET_ONE_PRODUCT"
export const EDIT_PRODUCT = "PRODUCT/EDIT_PRODUCT"
export const CLEAR_PRODUCT = "PRODUCT/CLEAR_PRODUCT"
export const DELETE_PRODUCT = "PRODUCT/DELETE_PRODUCT"
export const USER_GET_COUNT = "USER/USER_GET_COUNT"
export const ADD_AND_DELETE_CART = 'ADD_AND_DELETE_CART'
export const GET_CART = 'GET_CART'
export const CLEAR_COUNT_OF_CART = 'CLEAR_COUNT_OF_CART'
export const ADD_AND_DELETE_FAVORITES = 'ADD_AND_DELETE_FAVORITES'
export const GET_FAVORITES = 'GET_FAVORITES'
export const USER_GET_PRODUCT = "USER/GET_PRODUCT"
export const USER_GET_DETAIL = "USER/GET_DETAIL"

export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"